### ISSUE TITLE
Inyeccion de dependencias

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#1]
Buenas tardes Fabricio,
Tu tarea consiste en crear una nueva rama en nuestro repositorio con el objetivo específico de permitir la edición y la adición de dependencias y versiones al archivo "pom".
Esta tarea es crucial para mantener y mejorar la integridad y eficiencia de nuestro proyecto, ya que el archivo "pom" desempeña un papel fundamental en la gestión de las dependencias y la compilación del código.

**Comment by Flores-Fabricio-Alfredo** [comment]
Tareas Realizada, compañeros @NaimaFarja @Sofi231098 @Lguerrero2023 @marisolpatri77
