### ISSUE TITLE
crear controladores para el login y registro

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#10]
Buen dia Sofia,
Tu tarea consiste en crear los controladores correspondientes para las funcionalidades de "Login" y "LoginRegistro". A continuación, te proporciono las indicaciones necesarias:

Controlador de "Login":
Este controlador debe encargarse de manejar la lógica relacionada con la autenticación de los usuarios en el sistema.
Debes implementar métodos para recibir los datos de inicio de sesión, validarlos y autenticar al usuario correspondiente.
Además, asegúrate de manejar los posibles escenarios de inicio de sesión incorrecto y proporcionar mensajes de error adecuados al usuario.

Controlador de "LoginRegistro":
Este controlador tiene como objetivo gestionar el proceso de registro de nuevos usuarios en el sistema.
Debes desarrollar métodos para recibir los datos de registro, validarlos y almacenarlos en la base de datos del sistema.
Asegúrate de manejar adecuadamente los posibles errores durante el registro, como la existencia de un nombre de usuario ya utilizado o la falta de información obligatoria.
Recuerda que estos controladores son fundamentales para el correcto funcionamiento del sistema, por lo que debes asegurarte de implementar la lógica necesaria de manera eficiente y segura.

**Comment by Sofi231098** [comment]
Buenas


creé los controladores para las paginas login.html y login_registro.html para luego conectar y redericcionar con las otras paginas del proyecto.
También cree la capa entity donde estan las clases y atributos que se van a usar en las paginas html.
