### ISSUE TITLE
Crear capa model de usuarios (entity)

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#12]
Holaaa Sofia!

Se te ha asignado una tarea de gran importancia. Tu responsabilidad será desarrollar la capa de modelo de usuarios en el paquete Java denominado "entity".
Esta capa de modelo será esencial para el correcto funcionamiento y manejo de los datos de los usuarios dentro de nuestra aplicación. Deberás asegurarte de que la capa de modelo cumpla con los estándares de calidad y sea eficiente en el manejo de la información relacionada con los usuarios.

**Comment by Sofi231098** [comment]
Buenas.
 Cree la capa entity donde estan las clases y atributos que se van a usar en las paginas html. lohice desde la rama capaControler_login_loginRegistro para poder usarla en los controladores. Se trabajo en conjunto
