### ISSUE TITLE
Crear carpeta layouts, junto con los html de Header y Footer

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#23]
Buenas tardes Fabricio,
Tu tarea consiste en crear la carpeta "Layouts" junto con los archivos HTML correspondientes: "Header" para el encabezado del navegador, que incluirá el logotipo y el nombre de la página web, y "Footer" para el pie de página, donde se mostrará información relevante sobre la página web.
Saludos cordiales,

**Comment by Flores-Fabricio-Alfredo** [comment]
buenas noches compañeros ya realice mi tarea
