### ISSUE TITLE
Inyeccion de dependencias 

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#24]
Holaa Sofía!,

Tu tarea es implementar las inyecciones de dependencia en la capa del controlador (controller) y en la capa de entidad (entity) utilizando las anotaciones:
 "@Component" : para marcar una clase como un componente gestionado por Spring. 
"@Autowired":  para realizar la inyección de dependencias en Spring.
Saludos!!

**Comment by Sofi231098** [comment]
Buenas.
ya implementé las inyecciones en el LoginController y LoginRegistroController
