### ISSUE TITLE
Crear una rama nueva para modificar LoginController y crear un nuevo html

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#31]
Buenas noches Fabricio,
La tarea que se te asigno es crear un nuevo html para que el usuario admin pueda editar/eliminar el contenido de la pagina web, ademas de realizar modificaciones en el controlador de inicio de sesión con el objetivo de redireccionar a los usuarios administradores a la página correspondiente para realizar modificaciones en el contenido del sitio.

**Comment by Flores-Fabricio-Alfredo** [comment]
tarea realizada
