### ISSUE TITLE
Crea- edita la capa controller, entity, repository y service de PesoIdeal.

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#52]
Buenas tardes Fabricio!
Descripción de la tarea:

Crea y edita la capa Entity:
Crea una entidad para representar la información de una persona relacionada con el cálculo del Peso Ideal.
Define los atributos necesarios para almacenar los detalles de una persona, como el nombre, la edad, la altura y el género.
Implementa los métodos getters y setters para acceder y modificar los atributos de la entidad.

Crea y edita la capa Repository:
Crea un repositorio para manejar las operaciones de persistencia relacionadas con la entidad "Persona".
Define métodos para realizar consultas y modificaciones en la base de datos en relación a la entidad "Persona".
Implementa las operaciones de guardar, actualizar, eliminar y recuperar personas utilizando consultas a la base de datos.

Crea y edita la capa Service:
Crea un servicio para encapsular la lógica de negocio relacionada con el cálculo del Peso Ideal.
Implementa métodos en el servicio para calcular el Peso Ideal de una persona, utilizando fórmulas específicas según el género y la edad.
Utiliza el repositorio de personas para acceder a la información necesaria para el cálculo del Peso Ideal.

Crea y edita la capa Controller:
Crea un controlador para manejar las solicitudes relacionadas con el cálculo del Peso Ideal.
Implementa la lógica de manejo de solicitudes y respuestas en cada método del controlador.

**Comment by Flores-Fabricio-Alfredo** [comment]
tarea terminada
