### ISSUE TITLE
Crear nueva rama, modificar la capa controller y Entity

### ISSUE THREAD

**Issue by marisolpatri77** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#6]
Hola Equipo!!!
Crear una nueva rama para implementar una nueva funcionalidad en el proyecto.
La implementaciónes nuevas seran:
Capa Controller:  representará a la capa controladora, en este paquete se agruparán todas las clases java de tipo @Controller.
Entity: en este paquete se agruparán todas las clases java que representen las entidades del dominio del problema.

**Comment by NaimaFarja** [comment]
Creaion Controller y Entity destinas a Recetas
cree la rama "Creacion_Controller_Entity_Recetas" 
Dentro de ella Modifique la Capa Controller para realizar el mapeo de las paginas y Entity en la que agregue las clases y atributos.
