### ISSUE TITLE
Crear html para login y registro de usuarios.

### ISSUE THREAD

**Issue by NaimaFarja** [Flores-Fabricio-Alfredo/Grupo10_TPFinal#9]
Buen dia Sofia,

Se te ha asignado la tarea de crear dos ramas nuevas para implementar dos formularios específicos. La primera rama estará destinada al desarrollo del formulario de inicio de sesión. La segunda rama se enfocará en el formulario de registro de usuarios. 

Saludos!!

**Comment by Sofi231098** [comment]
buenas.

Ya creé las paginas html de logueo y registro de usuarios desde la rama creacion_html_login_loginRegistro.
La pagina login.html es para que el usuario, ya registrado, pueda acceder a la pagina.
La pagina loginRegistro.html es para que el usuario pueda registrarse en nuestra pagina
